// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBz7jc7T2Do2cpxmvLREIINqEeCWZWJb4',
    appId: '1:1007661198116:web:45d08c93113ec5fdfce1b1',
    messagingSenderId: '1007661198116',
    projectId: 'karyawan-437a8',
    authDomain: 'karyawan-437a8.firebaseapp.com',
    databaseURL: 'https://karyawan-437a8-default-rtdb.firebaseio.com',
    storageBucket: 'karyawan-437a8.appspot.com',
    measurementId: 'G-GLPZLLWDNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeG_jabbVqllkFmmO6hWGu0NLNcxY9TpM',
    appId: '1:1007661198116:android:c5e0d04f67ec4cf3fce1b1',
    messagingSenderId: '1007661198116',
    projectId: 'karyawan-437a8',
    databaseURL: 'https://karyawan-437a8-default-rtdb.firebaseio.com',
    storageBucket: 'karyawan-437a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtFEj9YVi6DxRviMRdYx19ToZEIF0OYa4',
    appId: '1:1007661198116:ios:e7e73e206a21ddf6fce1b1',
    messagingSenderId: '1007661198116',
    projectId: 'karyawan-437a8',
    databaseURL: 'https://karyawan-437a8-default-rtdb.firebaseio.com',
    storageBucket: 'karyawan-437a8.appspot.com',
    iosBundleId: 'com.example.utspab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtFEj9YVi6DxRviMRdYx19ToZEIF0OYa4',
    appId: '1:1007661198116:ios:e7e73e206a21ddf6fce1b1',
    messagingSenderId: '1007661198116',
    projectId: 'karyawan-437a8',
    databaseURL: 'https://karyawan-437a8-default-rtdb.firebaseio.com',
    storageBucket: 'karyawan-437a8.appspot.com',
    iosBundleId: 'com.example.utspab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBz7jc7T2Do2cpxmvLREIINqEeCWZWJb4',
    appId: '1:1007661198116:web:eedbb98878c03682fce1b1',
    messagingSenderId: '1007661198116',
    projectId: 'karyawan-437a8',
    authDomain: 'karyawan-437a8.firebaseapp.com',
    databaseURL: 'https://karyawan-437a8-default-rtdb.firebaseio.com',
    storageBucket: 'karyawan-437a8.appspot.com',
    measurementId: 'G-R553FRNTKT',
  );
}
